apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: docker-deploy-from-github
  title: Deploy Docker from GitHub Repo
  description: Create and deploy a Docker container from a GitHub repository URL.
spec:
  owner: user:guest
  type: service

  
  parameters:
    - title: GitHub Repository URL
      required: 
        - Github_URL
      properties:
        Github_URL:
          title: Enter you Github URL
          type: string
          description: Enter the github URL where your code exists
          ui:autofocus: true
          
# parameters:
#   - title: Fill in project details
#     required:
#       - name
#       - description
#       - owner
#     properties:
#       name:
#         title: Project Name
#         type: string
#         description: What’s the name of your project?
#         ui:autofocus: true
          
  steps:
    - id: fetch-template
      name: Fetch template files
      action: fetch:template
      input:
        url: ${{ parameters.Github_URL }}
        targetPath: .

    # - id: build_docker
    #   name: Build Docker Image
    #   action: shell:run
    #   input:
    #     workingDirectory: ${{ steps.clone.output.path }}
    #     command: |
    #       docker build -t my-image:latest .

     - id: build_docker
        name: Build Docker Image
        action: shell:run
        input:
          cwd: ${{ steps.clone.output.path }}
          command: docker 
          args: ["build", "-t", "my-image:latest", "."]
            

    # - id: deploy_docker
    #   name: Deploy Docker Container
    #   action: shell:run
    #   input:
    #     workingDirectory: ${{ steps.clone.output.path }}
    #     script: |
    #       docker run -d -p 8080:80 my-image:latest

    # - id: run-echo
    #   name: Echo Test
    #   action: shell:run
    #   input:
    #     command: echo
    #     args: ["Hello Backstage!"]
